### ISSUE TITLE
Conda package

### ISSUE THREAD

**Issue by woutdenolf** [ClearcodeHQ/pytest-redis#398]
For the time being we've added pytest-redis (and mirakuru) to own conda channel:

https://anaconda.org/esrf-bcu/pytest-redis

Would it be possible to add it to conda-forge?

**Comment by woutdenolf** [comment]
Shall I request a feedstock on conda-forge? One MR to https://github.com/conda-forge/staged-recipes will do.

Create conda recipe's:

```
grayskull pypi mirakuru --extras-require-test tests
grayskull pypi pytest-redis --extras-require-test tests
```

```yaml
{% set name = "mirakuru" %}
{% set version = "2.4.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mirakuru-{{ version }}.tar.gz
  sha256: ec84d4d81b4bca96cb0e598c6b3d198a92f036a0c1223c881482c02a98508226

build:
  skip: true  # [py<37]
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python
    - pip
  run:
    - python
    - psutil >=4.0.0  #  [not cygwin]

test:
  imports:
    - mirakuru
  commands:
    - pip check
    - pytest --pyargs mirakuru
  requires:
    - pip
    - pytest
    - pytest-cov
    - python-daemon

about:
  home: https://github.com/ClearcodeHQ/mirakuru
  summary: Process executor (not only) for tests.
  license: LGPL-3.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - fizyk
```

```yaml
{% set name = "pytest-redis" %}
{% set version = "2.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pytest-redis-{{ version }}.tar.gz
  sha256: 8a07520abed3cd341e8da1793059aa5717b02e56c43e7c76435db682cede10aa

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - pytest >=6.2.0
    - port-for >=0.6.0
    - mirakuru
    - redis-py

test:
  imports:
    - pytest_redis
  commands:
    - pip check
    - pytest --pyargs pytest_redis
  requires:
    - pip
    - pytest-cov
    - pytest-xdist
    - mock

about:
  home: https://github.com/ClearcodeHQ/pytest-redis
  summary: Redis fixtures and fixture factories for Pytest.
  license: GPL-3.0 & LGPL-3.0
  license_file:
    - COPYING.lesser
    - COPYING

extra:
  recipe-maintainers:
    - fizyk
```
